version: '3'
services:
  ma-textb-prozessanalyse-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ma-textb-prozessanalyse-backend
    container_name: ma-textb-prozessanalyse-backend
    expose:
     - "8000"
    ports:
     - "8000:8000"
  ma-textb-prozessanalyse-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ma-textb-prozessanalyse-frontend
    depends_on:
     - ma-textb-prozessanalyse-backend
    ports:
     - "3000:3000"
    expose:
     - "3000"
    links:
     - ma-textb-prozessanalyse-backend